[project]
name = "feature-one-anamoly-detection-mcp"
version = "0.1.0"
description = "MCP Server for hybrid anomaly detection on battery sensor data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.8.0",
    "numpy>=1.24.3",
    "pandas>=1.5.3",
    "scikit-learn>=1.2.2",
    "matplotlib>=3.7.1",
    "seaborn>=0.12.2",
    "tensorflow>=2.11.0",
]

[tool.setuptools.packages.find]
where = ["."]